server:
  port: 9999
  servlet:
    context-path: /jpa
spring:
  data:
    jpa:
      repositories:
        bootstrap-mode:
        enabled: true
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    password: jpa
    url: jdbc:p6spy:postgresql://localhost:5432/jpa
    username: jpa
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: true
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 20
  pid:
    file: jpa.pid
  application:
    name: JPARBAC
  security:
    user:
      name: admin
      password: admin
logging:
  level:
    org:
      hibernate:
        SQL: info

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: JPARBC
  try-host: http://localhost:${server.port}${server.servlet.context-path}

p6spy:
  config:
    appender: com.p6spy.engine.spy.appender.Slf4JLogger
    logMessageFormat: com.p6spy.engine.spy.appender.CustomLineFormat
    customLogMessageFormat: executionTime:%(executionTime) ms | 执行sql:%(sqlSingleLine)

