server:
  servlet:
    context-path: /jpa
spring:
  data:
    jpa:
      repositories:
        bootstrap-mode:
        enabled: true
  datasource:
    driver-class-name: ''
    password: jpa
    url: jdbc:postgresql://localhost:5432/jpa
    username: jpa
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: true
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 20
  pid:
    file: jpa.pid
  application:
    name: JPARBAC
logging:
  level:
    org:
      hibernate:
        SQL: trace


swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: JPARBC
  try-host: http://localhost:${server.port}${server.servlet.context-path}
